-- MySQL Script generated by MySQL Workbench
-- seg 13 fev 2023 05:12:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dev_db_sistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dev_db_sistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_db_sistema` ;
USE `dev_db_sistema` ;

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_grupo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(25) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `grupo` (`grupo` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de grupos de usuários.';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_modulo_controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_modulo_controller` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `controller` VARCHAR(100) NOT NULL,
  `use_as` VARCHAR(100) NULL DEFAULT NULL,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `restrict` ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_id_modulo_controller` (`controller` ASC, `id_modulo` ASC) VISIBLE,
  UNIQUE INDEX `use_as` (`use_as` ASC) VISIBLE,
  INDEX `fk_tb_acl_modulo_classe_tb_acl_modulo1_idx` (`id_modulo` ASC) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_modulo_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_modulo_routes` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `id_controller` INT(11) UNSIGNED NOT NULL,
  `id_parent` INT(11) UNSIGNED NULL DEFAULT NULL,
  `type` ENUM('any', 'get', 'post', 'put', 'head', 'options', 'delete', 'patch', 'match', 'resource', 'map', 'group') NOT NULL DEFAULT 'get',
  `route` VARCHAR(255) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `filter` LONGTEXT NULL DEFAULT NULL,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `restrict` ENUM('yes', 'no', 'inherit') NOT NULL DEFAULT 'inherit',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `route_controller_action_name_UNIQUE` USING BTREE (`type`, `route`, `action`, `name`) VISIBLE,
  INDEX `fk_tb_acl_rotas_tb_acl_modulo_classe1_idx` (`id_controller` ASC) VISIBLE,
  INDEX `fk_tb_acl_modulo_routes_id_parent` (`id_parent` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de rotas de menus.';

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_modulo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `modulo` VARCHAR(50) NOT NULL,
  `path` VARCHAR(50) NOT NULL,
  `namespace` VARCHAR(255) NOT NULL,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `homepage` INT(11) UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `restrict` ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `modulo` (`modulo` ASC) VISIBLE,
  UNIQUE INDEX `diretorio` (`path` ASC) VISIBLE,
  INDEX `fk_tb_acl_modulo_homepage` (`homepage` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de módulos. Módulos correspondem aos diretórios da aplicação: main, admin, etc...';

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu` (
  `id` INT(11) UNSIGNED NOT NULL,
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `id_grupo` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `editavel` ENUM('0', '1') NOT NULL DEFAULT '1',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_acl_menu_tb_pagina1_idx` (`id_modulo` ASC) VISIBLE,
  INDEX `fk_tb_acl_menu_tb_acl_grupo1_idx` (`id_grupo` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de menus';

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_sys_idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_sys_idioma` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `sigla` VARCHAR(7) NOT NULL,
  `label` VARCHAR(50) NULL DEFAULT NULL,
  `imagem` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sigla` (`sigla` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu_descricao` (
  `id_menu` INT(11) UNSIGNED NOT NULL,
  `id_idioma` INT(11) UNSIGNED NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keywords` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_idioma`, `id_menu`),
  INDEX `fk_tb_produto_descricao_tb_produto1_idx` (`id_menu` ASC) VISIBLE,
  INDEX `fk_tb_produto_descricao_tb_sys_idioma1_idx` (`id_idioma` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu_item` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_item` INT(11) UNSIGNED NOT NULL COMMENT 'Referencia a tabela (tb_acl_modulo_controller ou tb_acl_modulo_post) para a qual aponta o menu',
  `id_parent` INT(11) UNSIGNED NULL DEFAULT NULL COMMENT 'Campo para hierarquia do menu',
  `id_route` INT(11) NOT NULL DEFAULT 0,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `item_type` VARCHAR(50) NULL DEFAULT NULL COMMENT 'É o nome da tabela referenciada. Seria a tb_acl_modulo_controller (controller) ou tb_acl_modulo_post (post)',
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  `target` VARCHAR(20) NULL DEFAULT NULL,
  `ordem` INT(11) NOT NULL DEFAULT 0,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `divider` TINYINT(1) NOT NULL DEFAULT 0,
  `editavel` ENUM('0', '1') NOT NULL DEFAULT '1',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_tb_menu_item_id_item_post` (`id_item` ASC) VISIBLE,
  INDEX `fk_tb_acl_menu_item_id_parent` (`id_parent` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de itens do menus';

-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu_item_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu_item_descricao` (
  `id_item` INT(11) UNSIGNED NOT NULL,
  `id_idioma` INT(11) UNSIGNED NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `meta_description` VARCHAR(255) NULL DEFAULT NULL,
  `meta_title` VARCHAR(255) NULL DEFAULT NULL,
  `meta_keywords` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_idioma`, `id_item`),
  INDEX `fk_tb_menu_item_descricao_id_item` (`id_item` ASC) VISIBLE,
  INDEX `fk_tb_menu_item_descricao_id_idioma` (`id_idioma` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu_item_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu_item_menu` (
  `id_menu` INT(11) UNSIGNED NOT NULL,
  `id_item` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_item`, `id_menu`),
  INDEX `fk_tb_acl_menu_item_menu_id_menu` (`id_menu` ASC) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_menu_secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_menu_secao` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `secao` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de seções de menus. Seções correspondem ao local onde o menu se localizará: sidebar, header, footer, etc...';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_modulo_controller_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_modulo_controller_descricao` (
  `id_controller` INT(11) UNSIGNED NOT NULL,
  `id_idioma` INT(11) UNSIGNED NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `meta_description` VARCHAR(255) NOT NULL,
  `meta_title` VARCHAR(255) NOT NULL,
  `meta_keywords` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_idioma`, `id_controller`),
  INDEX `fk_tb_acl_modulo_controller_descricao_id_controller_id_item` (`id_controller` ASC, `id_idioma` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_modulo_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_modulo_grupo` (
  `id_grupo` INT(11) UNSIGNED NOT NULL,
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_grupo`, `id_modulo`),
  INDEX `fk_tb_acl_menu_grupo_id_grupo` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_acl_modulo_grupo_tb_acl_modulo1_idx` (`id_modulo` ASC) VISIBLE
)
ENGINE = InnoDB
COMMENT = 'Tabela para atribuições de menus a grupos de usuários.';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_pacote` (
  `id` INT(11) UNSIGNED NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `titulo` (`titulo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_pacote_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_pacote_modulo` (
  `id_pacote` INT(11) UNSIGNED NOT NULL,
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_pacote`, `id_modulo`),
  INDEX `fk_tb_pacote_modulo_id_modulo` (`id_modulo` ASC) VISIBLE,
  INDEX `fk_tb_acl_pacote_modulo_id_pacote` USING BTREE (`id_pacote`) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_funcionario` (
  `id` INT(11) UNSIGNED NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_usuario` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_grupo` INT(11) UNSIGNED NOT NULL,
  `id_funcionario` INT(11) UNSIGNED NULL DEFAULT NULL,
  `id_gestor` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  `permissao` SMALLINT(4) UNSIGNED ZEROFILL NOT NULL DEFAULT 1111,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login` (`login` ASC) VISIBLE,
  INDEX `fk_tb_acl_usuario_id_grupo` (`id_grupo` ASC) VISIBLE,
  INDEX `fk_tb_acl_usuario_id_funcionario` (`id_funcionario` ASC) VISIBLE
)
ENGINE = InnoDB
COMMENT = 'Tabela para cadastro de usuários';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_sys_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_sys_config` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Número sequencial da tabela.',
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `config` VARCHAR(255) NOT NULL,
  `value` LONGTEXT NULL DEFAULT NULL COMMENT 'Endereço do website',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC, `config` ASC) VISIBLE,
  INDEX `fk_tb_sys_config_id_modulo` (`id_modulo` ASC) VISIBLE
)
ENGINE = InnoDB
COMMENT = 'Tabela de configurações do site';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_usuario_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_usuario_config` (
  `id_usuario` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Número sequencial da tabela.',
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `id_config` INT(11) UNSIGNED NOT NULL,
  `value` LONGTEXT NULL DEFAULT NULL COMMENT 'Endereço do website',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`, `id_config`),
  INDEX `fk_tb_acl_usuario_config_id_config` (`id_config` ASC) VISIBLE,
  INDEX `fk_tb_acl_usuario_config_id_modulo` (`id_modulo` ASC) VISIBLE
)
ENGINE = InnoDB
COMMENT = 'Tabela de configurações do site';


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_usuario_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_usuario_imagem` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `filesize` INT(10) UNSIGNED NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `privada` ENUM('0', '1') NOT NULL DEFAULT '0',
  `status` ENUM('0', '1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `tb_acl_usuario_imagem_id_usuario` (`id_usuario` ASC) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_acl_usuario_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_acl_usuario_session` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) UNSIGNED NOT NULL,
  `id_modulo` INT(11) UNSIGNED NOT NULL,
  `token` VARCHAR(60) NULL DEFAULT NULL,
  `ip` VARCHAR(39) NOT NULL,
  `user_agent` VARCHAR(255) NOT NULL,
  `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `expired_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_acl_usuario_session_id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_acl_usuario_session_id_modulo` (`id_modulo` ASC) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_sys_dicionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_sys_dicionario` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `palavra` TEXT NOT NULL,
  `definicao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dev_db_sistema`.`tb_sys_idioma_dicionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_db_sistema`.`tb_sys_idioma_dicionario` (
  `id_idioma` INT(11) UNSIGNED NOT NULL,
  `id_palavra` INT(11) UNSIGNED NOT NULL,
  `traducao` TEXT NOT NULL,
  PRIMARY KEY (`id_idioma`, `id_palavra`),
  INDEX `fk_tb_sys_idioma_id_palavra` (`id_palavra` ASC) VISIBLE,
  INDEX `fk_tb_sys_idioma_id_idioma` (`id_idioma` ASC) VISIBLE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
